baseURL = 'https://flowsnr.github.io'
languageCode = 'en-us'
title = 'Lea Wiesner'
theme = 'custom'

[params]
  author = 'Lea Maria Wiesner'
  description = 'Personal website of Lea Maria Wiesner'
  profileImage = '/images/profile.jpg'
  github = 'https://github.com/LWsnr'
  linkedin = 'https://www.linkedin.com/in/florian-wiesner-profile/'
  googlescholar = 'https://scholar.google.com/citations?user=rvqCcpgAAAAJ&hl=en'
  x = 'https://x.com/f_wiesner'

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[[menu.main]]
  name = 'Home'
  url = '/'
  weight = 1

[[menu.main]]
  name = 'Blog'
  url = '/blog/'
  weight = 2

[[menu.main]]
  name = 'About'
  url = '/about/'
  weight = 3

[[menu.main]]
  name = 'Research'
  url = '/research/'
  weight = 4

[[menu.main]]
  name = 'Hobbies'
  url = '/hobbies/'
  weight = 5

[[menu.main]]
  name = 'News'
  url = '/news/'
  weight = 6
